package com.h5radar.radar.domain;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors;
import org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers;
import org.springframework.test.web.reactive.server.WebTestClient;
import org.springframework.test.web.servlet.client.MockMvcWebTestClient;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.web.context.WebApplicationContext;

import com.h5radar.radar.RadarApplication;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = RadarApplication.class)
public abstract class AbstractIntegrationTests extends AbstractAnyTests {
  /*
   * Auth header with sub equal to alice
   */
  @SuppressWarnings("checkstyle:LineLength")
  protected static final String AUTHORIZATION_HEADER = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUT1Z3ekNsQVdIM2hzVDAtV1Jhemx4Z1k4RXhBd0NPb2hNTEg4dXEtVkM4In0.eyJleHAiOjE3NTA5NDI3MjUsImlhdCI6MTc1MDk0MjQyNSwiYXV0aF90aW1lIjoxNzUwOTQwMTA2LCJqdGkiOiI1M2RlMmZmZS01YzBjLTQ3MGUtYWUwZi03Zjg5ZTk0ODUwNWUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgxODAvcmVhbG1zL2g1cmFkYXIiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiNTQ4M2NiZTgtMTVjZC00YmY1LTkxMWUtNmNhNDU1ZTUzM2M5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBwLXVpIiwic2lkIjoiYTE0Mzk0MjMtNjU0Zi00MzkwLTkyOTItNWIxZWY1NGU5YWJkIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwczovL2FwcC5oNXJhZGFyLnJ1IiwiaHR0cDovL2xvY2FsaG9zdDo1MTczIiwiaHR0cHM6Ly9hcHAuaDVyYWRhci5jb20iXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImVudGVycHJpc2UiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoiQWxpY2UgTGlkZGVsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYWxpY2UiLCJnaXZlbl9uYW1lIjoiQWxpY2UiLCJmYW1pbHlfbmFtZSI6IkxpZGRlbCIsImVtYWlsIjoiYWxpY2VAZXhhbXBsZS5jb20ifQ.EvJRB4ZtS_bun0l_i-pgxe5w58VOXjPZk3ZkLYIh0nDMvMzEgQvC9dRTn_1LHqt_aNK_cdTYwgtPhtRJuDztjvePDx7XiyxrHRtjtE8_brUL_SOXeZ6ohI9nV-1_3OKFPOWvwZO6UoXvM_ybd0zDNmdDUllj1O3u_iyJtDuamezY17KdsVjgeUH_u7l9HqPbXOi1LBXspK6xlGEUmNEAcuwGx6U2dTEjpiLzTydFKSsMWZmkLgE7qSUR5QYwLACPW9NNyrIEzKQMH30yA-5PX_5Nm5gb3MIpSnGMOGWIQ5SUDcSmC4dG_CQC_4xU0ZPo7i1IEOh9DzUtad08iB3r6w";

  // @Autowired
  protected WebTestClient webTestClient;

  @Autowired
  public void setWebApplicationContext(final WebApplicationContext context) {
    webTestClient = MockMvcWebTestClient.bindToApplicationContext(context)
        .apply(SecurityMockMvcConfigurers.springSecurity())
        .defaultRequest(MockMvcRequestBuilders.get("/").with(SecurityMockMvcRequestPostProcessors.csrf()))
        .configureClient()
        .build();
  }
}
