#
# This file run keycloak
#
# http://localhost:8080/admin/master/console/ with admin/admin
#
# Important:
# This configuration is intended for development purpose
#
version: '3.8'
services:
  keycloak-postgres:
    image: postgres:15.6
    container_name: keycloak-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak-web:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak-web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloak-postgres
    ports:
      - 8080:8080
volumes:
  postgres_data: